function plot_FiveLinkWalker(q,bn)
% plot the robot using forward kinematic function generated by FROST
% q = [x,z,theta,q1_r,q2_r,q1_l,q2_l]' [7x1]

addpath gen_byFROST\

pos_CoM = pos_CoM_func(q);
pos_hip = pos_hip_func(q);
pos_head = pos_head_func(q);
pos_knee_r = pos_knee_r_func(q);
pos_knee_l = pos_knee_l_func(q);
pos_toe_r = pos_toe_r_func(q);
pos_toe_l = pos_toe_l_func(q);

if nargin > 1
    r_color = [1, 0, 0] + [0, 1, 1] * bn;
    b_color = [0, 0, 1] + [1, 1, 0] * bn;
    k_color = [0, 0, 0] + [1, 1, 1] * 0.5 * bn;
else
    r_color = [1 0 0];
    b_color = [0 0 1];
    k_color = [0 0 0];
end

% figure; 
hold on;
% plot link
plot([pos_hip(1) pos_head(1)], [pos_hip(3) pos_head(3)],'-','LineWidth',3,'Color',k_color);
plot([pos_hip(1) pos_knee_r(1)], [pos_hip(3) pos_knee_r(3)],'-','LineWidth',3,'Color',r_color);
plot([pos_hip(1) pos_knee_l(1)], [pos_hip(3) pos_knee_l(3)],'-','LineWidth',3,'Color',b_color);
plot([pos_toe_r(1) pos_knee_r(1)], [pos_toe_r(3) pos_knee_r(3)],'-','LineWidth',3,'Color',r_color);
plot([pos_toe_l(1) pos_knee_l(1)], [pos_toe_l(3) pos_knee_l(3)],'-','LineWidth',3,'Color',b_color);
% plot joint/point
plot(pos_CoM(1),pos_CoM(3),'ro','MarkerSize',13,'MarkerFaceColor',r_color);
plot(pos_hip(1),pos_hip(3),'mo','MarkerSize',3,'MarkerFaceColor','m');
plot(pos_knee_r(1),pos_knee_r(3),'mo','MarkerSize',3,'MarkerFaceColor','m');
plot(pos_knee_l(1),pos_knee_l(3),'mo','MarkerSize',3,'MarkerFaceColor','m');
plot(pos_toe_r(1),pos_toe_r(3),'mo','MarkerSize',3,'MarkerFaceColor','m');
plot(pos_toe_l(1),pos_toe_l(3),'mo','MarkerSize',3,'MarkerFaceColor','m');

axis equal

end